---
title: "T and NK Cells Annotation"
author: "Mohmed Abdalfttah"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

## Libraries

```{r}
library(Seurat)
library(cowplot)
library(tidyverse)
library(glue)
library(here)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

```{r}
Analysis = function(obj, res, dim){
  obj <-  SCTransform(obj, vst.flavor = "v2", verbose = TRUE, vars.to.regress = c("percent.mt"))
  #obj <- NormalizeData(obj)
  #obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 3000)
  #obj <- ScaleData(obj)
  obj <- RunPCA(obj, features = VariableFeatures(object = obj))
  print(ElbowPlot(object = obj, ndims = 50))
  obj = RunUMAP(object = obj, dims = dim, verbose = F)
  obj = FindNeighbors(object = obj, dims =  dim, verbose = F)
  obj = FindClusters(object = obj, resolution = res, verbose = F)
}
Save_Markers = function(Markers, Path_write){
  mgs_ls = lapply(sort(unique(Markers$cluster)), function(clust) {
  Markers %>%
    dplyr::filter(cluster == clust & pct.1 > 0.5) %>%
    dplyr::arrange(dplyr::desc(avg_log2FC))
    })
  names(mgs_ls) = glue("cluster-{sort(unique(Markers$cluster))}")
  openxlsx::write.xlsx(mgs_ls, file = Path_write)

}
```



```{r}
them_plot <- theme(
  plot.title = element_text(size = 8),
  axis.title.x = element_text(size = 8),
  axis.title.y = element_text(size = 8),
  axis.text.x = element_text(size = 8),
  axis.text.y = element_text(size = 8),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8))
cols = ggsci::pal_igv()(50)
```


## Setting parameters
Loading necessary paths and parameters
```{r}
source(here::here("misc/paths.R"))
```

```{r}
se_obj <- "{annot_tme}/{robj_dir}/TNKILC_obj.rds" %>%
  here::here() %>%
  glue::glue() %>%
  readRDS(.)
```

```{r}
DimPlot(se_obj, group.by = "ClusterTop")
```


```{r}
se_obj <- Analysis(obj = se_obj, res = c(0.2, 0.3, 0.4, 0.5), dim = 1:30)
```

```{r, fig.width=10}
DimPlot(se_obj, group.by = c("SCT_snn_res.0.2", "SCT_snn_res.0.3", "SCT_snn_res.0.3", "SCT_snn_res.0.4"), cols = cols)
```
Map Cononical Marker Genes



```{r, fig.width=20, fig.height=20, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
FeaturePlot(se_obj, features = c("PTPRC", "CD3D", "CD4", "CCR7", "IL7R", "CD8A", "CD8B","FOXP3", "NKG7", "XCL1", "NCR1", "NCR3","KLRD1","GZMH")) +
  DimPlot(se_obj, cols = ggsci::pal_igv()(50), label = T, group.by = c("SCT_snn_res.0.4"), label.size = 5) +
    DimPlot(se_obj, cols = ggsci::pal_igv()(50), label = T, group.by = c( "ClusterMidway"), label.size = 5)

VlnPlot(se_obj, features = c("PTPRC", "CD3D", "CD4", "CCR7", "IL7R", "CD8A", "CD8B","FOXP3", "NKG7", "XCL1", "NCR1", "NCR3","KLRD1","GZMH"),
        group.by = "SCT_snn_res.0.4", cols = cols)
```

```{r}
se_obj@meta.data <- se_obj@meta.data %>%
    dplyr::mutate(
        annotation_lvl1 = dplyr::case_when(
            ClusterMidway == "TCD4" ~ "CD4",
            ClusterMidway == "TCD8" ~ "CD8",
            ClusterMidway == "NK" ~ "NK",
            ClusterMidway == "TZBTB16" ~ "NK",
            ClusterMidway == "Tgd" ~ "CD8",
            ClusterMidway == "ILC" ~ "ILC",
            )
        )
DimPlot(se_obj, group.by = c("annotation_lvl1")) 
```

```{r}
se_obj_list <- SplitObject(se_obj, split.by = "annotation_lvl1")
```

# CD8 T Cells
```{r}
se_obj_list$CD8 <- Analysis(se_obj_list$CD8, res = c(0.2, 0.3, 0.4), dim = 1:30)
```

```{r, fig.width=20, fig.height=20, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
FeaturePlot(se_obj_list$CD8, features = c("PTPRC", "CD3D", "CD4", "CCR7", "IL7R", "CD8A", "CD8B","FOXP3", "NKG7", "XCL1", "NCR1", "NCR3","KLRD1","GZMH")) +
  DimPlot(se_obj_list$CD8, cols = ggsci::pal_igv()(50), label = T, group.by = c("SCT_snn_res.0.2"), label.size = 5) +
    DimPlot(se_obj_list$CD8, cols = ggsci::pal_igv()(50), label = F, group.by = c( "ClusterFull"), label.size = 5)

VlnPlot(se_obj_list$CD8, features = c("PTPRC", "CD3D", "CD4", "CCR7", "IL7R", "CD8A", "CD8B","FOXP3", "NKG7", "XCL1", "NCR1", "NCR3","KLRD1","GZMH"),
        group.by = "SCT_snn_res.0.2", cols = cols)
```

```{r}
Idents(se_obj_list$CD8) <- se_obj_list$CD8$SCT_snn_res.0.2
markers <- FindAllMarkers(se_obj_list$CD8, only.pos = TRUE)
```

```{r, fig.width=10}
markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10
DoHeatmap(se_obj_list$CD8, features = top10$gene) + NoLegend()
```

```{r}
"{annot_tme}/{robj_dir}/markers_CD8.xlsx" %>%
    glue::glue() %>%
    here::here() %>%
    Save_Markers(Markers =markers, Path_write = .)

```

```{r}
top10
```

```{r}
se_obj_list$CD8@meta.data <- se_obj_list$CD8@meta.data %>%
    dplyr::mutate(
        annotation_lvl2 = dplyr::case_when(
            SCT_snn_res.0.2 == 0 ~ "CD8 T CXCL13+",
            SCT_snn_res.0.2 == 1 ~ "CD8 T GZMK+",
            SCT_snn_res.0.2 == 2 ~ "Tgd",
            SCT_snn_res.0.2 == 3 ~ "CD8 T IL17A+",
            SCT_snn_res.0.2 == 4 ~ "CD8 T KLRB1+",
            SCT_snn_res.0.2 == 5 ~ "CD8 T Proliferation",
            SCT_snn_res.0.2 == 6 ~ "Doublet",
            SCT_snn_res.0.2 == 7 ~ "CD8 T CXCL8+"
            )
        )
DimPlot(se_obj_list$CD8, group.by = c("annotation_lvl2")) 

```


# CD4 T Cells
```{r}
se_obj_list$CD4 <- Analysis(se_obj_list$CD4, res = c(0.2, 0.3, 0.4), dim = 1:30)
```

```{r, fig.width=10}
DimPlot(se_obj_list$CD4, cols = ggsci::pal_igv()(50), label = F, group.by = c("SCT_snn_res.0.2", "SCT_snn_res.0.3", "SCT_snn_res.0.4"), label.size = 5, ncol = 2)

```

```{r, fig.width=20, fig.height=20, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
FeaturePlot(se_obj_list$CD4, features = c("PTPRC", "CD3D", "CD4", "CCR7", "IL7R", "CD8A", "CD8B","FOXP3", "NKG7", "XCL1", "NCR1", "NCR3","KLRD1","GZMH")) +
  DimPlot(se_obj_list$CD4, cols = ggsci::pal_igv()(50), label = T, group.by = c("SCT_snn_res.0.2"), label.size = 5) +
    DimPlot(se_obj_list$CD4, cols = ggsci::pal_igv()(50), label = F, group.by = c( "ClusterFull"), label.size = 5)

VlnPlot(se_obj_list$CD4, features = c("PTPRC", "CD3D", "CD4", "CCR7", "IL7R", "CD8A", "CD8B","FOXP3", "NKG7", "XCL1", "NCR1", "NCR3","KLRD1","GZMH"),
        group.by = "SCT_snn_res.0.2", cols = cols)
```

```{r}
Idents(se_obj_list$CD4) <- se_obj_list$CD4$SCT_snn_res.0.2
markers <- FindAllMarkers(se_obj_list$CD4, only.pos = TRUE)
```

```{r, fig.width=10}
markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10
DoHeatmap(se_obj_list$CD4, features = top10$gene) + NoLegend()
```

```{r}
"{annot_tme}/{robj_dir}/markers_CD4.xlsx" %>%
    glue::glue() %>%
    here::here() %>%
    Save_Markers(Markers =markers, Path_write = .)
```

```{r}
top10
```

```{r}
se_obj_list$CD4@meta.data <- se_obj_list$CD4@meta.data %>%
    dplyr::mutate(
        annotation_lvl2 = dplyr::case_when(
            SCT_snn_res.0.2 == 0 ~ "Treg",
            SCT_snn_res.0.2 == 1 ~ "CD4 T CM",
            SCT_snn_res.0.2 == 2 ~ "CD4 T Naive",
            SCT_snn_res.0.2 == 3 ~ "CD4 T HSPA+",
            SCT_snn_res.0.2 == 4 ~ "CD4 T Proliferation",
            SCT_snn_res.0.2 == 5 ~ "CD4 T CXCL13",
            SCT_snn_res.0.2 == 6 ~ "CD4 T Activated",
            SCT_snn_res.0.2 == 7 ~ "CD4 T Cytotoxic",
            SCT_snn_res.0.2 == 8 ~ "Doublet",
            SCT_snn_res.0.2 == 9 ~ "CD4 T Cytotoxic"
            )
        )
DimPlot(se_obj_list$CD4, group.by = c("annotation_lvl2"), cols = cols) 
```

# NK Cells

```{r}
se_obj_list$NK <- Analysis(se_obj_list$NK, res = c(0.2, 0.3, 0.4), dim = 1:30)
```

```{r, fig.width=10}
DimPlot(se_obj_list$NK, cols = ggsci::pal_igv()(50), label = F, group.by = c("SCT_snn_res.0.2", "SCT_snn_res.0.3", "SCT_snn_res.0.4"), label.size = 5, ncol = 2)

```

```{r, fig.width=20, fig.height=20, echo=FALSE, error=FALSE, warning=FALSE, message=FALSE}
FeaturePlot(se_obj_list$NK, features = c("PTPRC", "CD3D", "CD4", "CCR7", "IL7R", "CD8A", "CD8B","FOXP3", "NKG7", "XCL1", "NCR1", "NCR3","KLRD1","GZMH")) +
  DimPlot(se_obj_list$NK, cols = ggsci::pal_igv()(50), label = T, group.by = c("SCT_snn_res.0.3"), label.size = 5) +
    DimPlot(se_obj_list$NK, cols = ggsci::pal_igv()(50), label = F, group.by = c( "ClusterFull"), label.size = 5)

VlnPlot(se_obj_list$NK, features = c("PTPRC", "CD3D", "CD4", "CCR7", "IL7R", "CD8A", "CD8B","FOXP3", "NKG7", "XCL1", "NCR1", "NCR3","KLRD1","GZMH"),
        group.by = "SCT_snn_res.0.3", cols = cols)
```

```{r}
Idents(se_obj_list$NK) <- se_obj_list$NK$SCT_snn_res.0.3
markers <- FindAllMarkers(se_obj_list$NK, only.pos = TRUE)
```

```{r, fig.width=10}
markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10
DoHeatmap(se_obj_list$NK, features = top10$gene) + NoLegend()
```

```{r}
"{annot_tme}/{robj_dir}/markers_NK.xlsx" %>%
    glue::glue() %>%
    here::here() %>%
    Save_Markers(Markers =markers, Path_write = .)
```

```{r}
top10
```

```{r, fig.width=10, fig.height=10}
se_obj_list$NK@meta.data <- se_obj_list$NK@meta.data %>%
    dplyr::mutate(
        annotation_lvl2 = dplyr::case_when(
            SCT_snn_res.0.3 == 0 ~ "NK GZMA+",
            SCT_snn_res.0.3 == 1 ~ "NK CD16-hi",
            SCT_snn_res.0.3 == 2 ~ "NK XCL1+",
            SCT_snn_res.0.3 == 3 ~ "CD8 T GZMH+",
            SCT_snn_res.0.3 == 4 ~ "CD8 T Proliferation"

            )
        )
DimPlot(se_obj_list$NK, group.by = c("annotation_lvl2"), cols = cols) 
```

# ILC
```{r}
se_obj_list$ILC$annotation_lvl1 <- "ILC"
se_obj_list$ILC$annotation_lvl2 <- "ILC"

```

# Merge All objects together 

```{r}
se_obj <- merge(x = se_obj_list[[1]], y = se_obj_list[2:length(se_obj_list)])
```

```{r}
se_obj <- Analysis(obj = se_obj, res = 0, dim = 1:30)
```


```{r, fig.width=10, fig.height=10}
DimPlot(se_obj, group.by = c("annotation_lvl1", "annotation_lvl2"), cols = cols)

```

```{r}
se_obj <- "{annot_tme}/{robj_dir}/TNKILC_obj_Annotated.rds" %>%
  here::here() %>%
  glue::glue() %>%
  saveRDS(object = se_obj)

```

```{r}
sessionInfo()
```

