---
title: "TME Pilka Combined"
author: "Mohmed Abdalfttah"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

```{r}
Analysis = function(obj, res, dim){
  obj <-  SCTransform(obj, vst.flavor = "v2", verbose = TRUE, vars.to.regress = c("percent.mt"))
  #obj <- NormalizeData(obj)
  #obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 3000)
  #obj <- ScaleData(obj)
  obj <- RunPCA(obj, features = VariableFeatures(object = obj))
  print(ElbowPlot(object = obj, ndims = 50))
  obj = RunUMAP(object = obj, dims = dim, verbose = F)
  obj = FindNeighbors(object = obj, dims =  dim, verbose = F)
  obj = FindClusters(object = obj, resolution = res, verbose = F)
}

Save_Markers = function(Markers, Path_write){
  mgs_ls = lapply(sort(unique(Markers$cluster)), function(clust) {
  Markers %>%
    dplyr::filter(cluster == clust & pct.1 > 0.5) %>%
    dplyr::arrange(dplyr::desc(avg_log2FC))
    })
  names(mgs_ls) = glue("cluster-{sort(unique(Markers$cluster))}")
  openxlsx::write.xlsx(mgs_ls, file = Path_write)

}

```

## Libraries

```{r}
library(Seurat)
library(cowplot)
library(tidyverse)
library(glue)
library(here)
cols = ggsci::pal_igv()(50)
```


```{r}
them_plot <- theme(
  plot.title = element_text(size = 8),
  axis.title.x = element_text(size = 8),
  axis.title.y = element_text(size = 8),
  axis.text.x = element_text(size = 8),
  axis.text.y = element_text(size = 8),
  legend.title = element_text(size = 8),
  legend.text = element_text(size = 8))

```

## Setting parameters
Loading necessary paths and parameters
```{r}
source(here::here("misc/paths.R"))
```

```{r}
files = c("B_obj_Annotated.rds", "Mast_obj.rds", "Myeloid_obj_Annotated.rds", "Plasma_obj.rds", "Strom_obj_Annotated.rds", "TNKILC_obj_Annotated.rds")

se_obj_list <- lapply(X = files, FUN = function(obj){
  "{annot_tme}/{robj_dir}/{obj}" %>%
    here::here() %>%
    glue::glue() %>%
    readRDS(file = .)
  
})
```

```{r}
DimPlot(se_obj_list[[1]], group.by = c("annotation_lvl2"), cols = cols) 
DimPlot(se_obj_list[[3]], group.by = c("annotation_lvl2"), cols = cols) 
DimPlot(se_obj_list[[5]], group.by = c("annotation_lvl2"), cols = cols) 
DimPlot(se_obj_list[[6]], group.by = c("annotation_lvl2"), cols = cols) 

```

```{r}
se_obj_list[[1]]$annotation_lvl1 <- se_obj_list[[1]]$ClusterTop
se_obj_list[[2]]$annotation_lvl1 <- se_obj_list[[2]]$ClusterTop
se_obj_list[[3]]$annotation_lvl1 <- se_obj_list[[3]]$ClusterTop
se_obj_list[[4]]$annotation_lvl1 <- se_obj_list[[4]]$ClusterTop
se_obj_list[[5]]$annotation_lvl1 <- se_obj_list[[5]]$ClusterTop
se_obj_list[[6]]$annotation_lvl1 <- se_obj_list[[6]]$ClusterTop

DimPlot(se_obj_list[[1]], group.by = c("annotation_lvl1"), cols = cols) 
DimPlot(se_obj_list[[2]], group.by = c("annotation_lvl1"), cols = cols) 
DimPlot(se_obj_list[[3]], group.by = c("annotation_lvl1"), cols = cols) 
DimPlot(se_obj_list[[4]], group.by = c("annotation_lvl1"), cols = cols) 
DimPlot(se_obj_list[[5]], group.by = c("annotation_lvl1"), cols = cols) 
DimPlot(se_obj_list[[6]], group.by = c("annotation_lvl1"), cols = cols) 
```


```{r}
se_obj_list[[1]]$annotation_lvl2 <- se_obj_list[[1]]$annotation_lvl2
se_obj_list[[2]]$annotation_lvl2 <- se_obj_list[[2]]$ClusterTop
se_obj_list[[3]]$annotation_lvl2 <- se_obj_list[[3]]$annotation_lvl2
se_obj_list[[4]]$annotation_lvl2 <- se_obj_list[[4]]$ClusterTop
se_obj_list[[5]]$annotation_lvl2 <- se_obj_list[[5]]$annotation_lvl2
se_obj_list[[6]]$annotation_lvl2 <- se_obj_list[[6]]$annotation_lvl2
```


```{r}
DimPlot(se_obj_list[[1]], group.by = c("annotation_lvl2"), cols = cols) 
DimPlot(se_obj_list[[2]], group.by = c("annotation_lvl2"), cols = cols) 
DimPlot(se_obj_list[[3]], group.by = c("annotation_lvl2"), cols = cols) 
DimPlot(se_obj_list[[4]], group.by = c("annotation_lvl2"), cols = cols) 
DimPlot(se_obj_list[[5]], group.by = c("annotation_lvl2"), cols = cols) 
DimPlot(se_obj_list[[6]], group.by = c("annotation_lvl2"), cols = cols) 
```

# Merge

```{r}
se_obj <- merge(x = se_obj_list[[1]], se_obj_list[2:length(se_obj_list)])
```



```{r}
se_obj <- Analysis(obj = se_obj, res = 0.2, dim = 1:40)
```

```{r}
Idents(se_obj) = se_obj$annotation_lvl2
all.markers <- FindAllMarkers(se_obj, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
```

# Save
```{r}
"{annot_tme}/{robj_dir}/merged_annotated_tme.rds" %>%
    here::here() %>%
    glue::glue() %>%
    saveRDS(object = se_obj)
```

```{r}
"{annot_tme}/{robj_dir}/markers_annotation_lvl2.rds" %>%
    here::here() %>%
    glue::glue() %>%
    saveRDS(object = all.markers)

```

```{r}
sessionInfo()
```

