---
author: "Mohamed Abdalfttah"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
  Sample: "Default!"
title: "6.1 Deconv Analysis - `r params$Sample`"
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

```{r, warning=FALSE, message=FALSE}
library(CellChat)
library(patchwork)
library(Seurat)
library(ggplot2)
library(presto)
cols <- ggsci::pal_igv()(50)
```

```{r}
them_plot <- theme(
    plot.title = element_text(size = 25),
    axis.title = element_text(size = 25),
    axis.text = element_text(size = 25),
    legend.title = element_text(size = 25),
    legend.text = element_text(size = 25),
    strip.text = element_text(size = 25), # For facet labels
    plot.caption = element_text(size = 25), # For plot caption if used
    plot.subtitle = element_text(size = 25) # For plot subtitle if used
  )
```

```{r}
Analysis = function(obj, res, dim){
  obj <-  SCTransform(obj, vst.flavor = "v2", verbose = F, vars.to.regress = c("percent.mt"))
  #obj <- NormalizeData(obj)
  #obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 3000)
  #obj <- ScaleData(obj)
  obj <- RunPCA(obj, features = VariableFeatures(object = obj), verbose = F)
  print(ElbowPlot(object = obj, ndims = 50), verbose = F)
  obj = RunUMAP(object = obj, dims = dim, verbose = F)
  obj = FindNeighbors(object = obj, dims =  dim, verbose = F)
  obj = FindClusters(object = obj, resolution = res, verbose = F)
}
```

```{r}
source(here::here("misc/paths.R"))
```

```{r}
se_obj <- "scRNAseq/MSS_Pellka_epin_epit_tme_processed.rds" %>%
  here::here() %>%
  glue::glue() %>%
  readRDS(file = .)
```


```{r}
se_obj@meta.data <- se_obj@meta.data %>%
  mutate(annotation_lvl1 = case_when(
    ClusterTop == "Epi" & is.na(annotation_lvl1) ~ "Epi",  # If ClusterTop is 'Epi' and annotation_lvl1 is NA, assign "Epi"
    ClusterTop == "Normal Epi" & is.na(annotation_lvl1) ~ "Normal Epi",  # If ClusterTop is 'Normal Epi' and annotation_lvl1 is NA, assign "Normal Epi"
    TRUE ~ annotation_lvl1  # Otherwise, keep the existing value of annotation_lvl1
  ))

```

```{r, fig.width=10, fig.height=10}
DimPlot(se_obj, group.by = c("annotation_lvl1"), cols = ggsci::pal_igv()(50),raster = F) + theme(legend.text = element_text(size = 25)) 

DimPlot(se_obj, group.by = "annotation_lvl1", cols = ggsci::pal_igv()(50), raster = FALSE, 
        label = TRUE, label.size = 5, label.box = TRUE) + 
theme(legend.position = "none")  + them_plot
```

```{r, fig.width=20, fig.height=15}
DimPlot(se_obj, group.by = c("all_cells_lvl2"), cols = ggsci::pal_igv()(50),raster = F) + theme(legend.text = element_text(size = 25)) +
  guides(color = guide_legend(override.aes = list(size = 8)))
```

# Panel 1

UMAP of Level 1 Annotation 
```{r, fig.width=20, fig.height=15}
pdf(file = "figures/Fig_1/01_UMAP.pdf" %>% here::here() %>% glue::glue(), width = 10, height = 7)
DimPlot(se_obj, group.by = c("annotation_lvl1"), cols = ggsci::pal_igv()(50),raster = F) + them_plot +
  guides(color = guide_legend(override.aes = list(size = 10)))
dev.off()
```

# Panel 2

```{r}
se_obj@meta.data$Patient_ID <- sub("^([^_]*)_.*", "\\1", rownames(se_obj@meta.data))

data_summary <- se_obj@meta.data %>%
  group_by(Patient_ID, annotation_lvl1) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  group_by(Patient_ID) %>%
  mutate(Percentage = Count / sum(Count))

pdf(file = "figures/Fig_1/02_Barplot_Patients_Level1.pdf" %>% here::here() %>% glue::glue(), width = 10, height = 7)
# Create the normalized stacked bar plot
ggplot(data_summary, aes(x = Patient_ID, y = Percentage, fill = annotation_lvl1)) +
  geom_bar(stat = "identity", position = "fill") +  # Use position "fill" to normalize
  scale_y_continuous(labels = scales::percent_format()) +  # Format y-axis as percent
  labs(title = "Proportional Distribution of Cell Types Per Donor",
       x = "Patient",
       y = "Percentage",
       fill = "Cell Type") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
  scale_fill_manual(values = ggsci::pal_igv()(50)) +
  them_plot
dev.off()
```

# Panel 3

UMAP for Main marker genes

```{r, fig.width=15, fig.height=7}
png(filename = "figures/Fig_1/03_UMAP_Markers.png" %>% here::here() %>% glue::glue(), width = 1500, height = 500)
FeaturePlot(se_obj, features = c("EPCAM", "PTPRC", "CD3E", "CD8A", "IL7R", "NKG7", "MS4A1", "CD14", "MZB1", "COL1A1", "ENG", "KIT"), ncol = 6) & them_plot
dev.off()
```

# Panel 4

```{r}
png(filename = "figures/Fig_1/04_Vlnplot_Markers.png" %>% here::here() %>% glue::glue(), width = 1500, height = 1000)
VlnPlot(se_obj, features = c("EPCAM", "PTPRC", "CD3E", "CD8A", "IL7R", "NKG7", "MS4A1", "CD14", "MZB1", "COL1A1", "ENG", "KIT"), ncol = 4, group.by = "annotation_lvl1", cols = ggsci::pal_igv()(50), pt.size = 0) & them_plot
dev.off()

```

```{r}
pdf(file = "figures/Fig_1/04_Vlnplot_Markers.pdf" %>% here::here() %>% glue::glue(), width = 15, height = 10)
VlnPlot(se_obj, features = c("EPCAM", "PTPRC", "CD3E", "CD8A", "IL7R", "NKG7", "MS4A1", "CD14", "MZB1", "COL1A1", "ENG", "KIT"), ncol = 4, group.by = "annotation_lvl1", cols = ggsci::pal_igv()(50), pt.size = 0) & them_plot
dev.off()

```


# Supplementry Fig 1

Panel 1

We don't need TP1 to TP7, we just make it Tumor

```{r}
se_obj@meta.data <- se_obj@meta.data %>% 
  mutate(all_cells_lvl2 = if_else(all_cells_lvl2 %in% paste("TP", 1:7, sep = ""), "Tumor", all_cells_lvl2))
```

Panel 1
```{r}
png(filename =  "figures/Fig_1/Supp_01_UMAP.png" %>% here::here() %>% glue::glue(), width = 1200, height = 700)
DimPlot(se_obj, group.by = c("all_cells_lvl2"), cols = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50)),raster = F) + them_plot +
  guides(color = guide_legend(override.aes = list(size = 10)))
dev.off()
```

```{r}
# Define custom colors
library(ggsci)
library(Seurat)
library(ggplot2)

library(Seurat)
library(ggsci)
library(ggplot2)

# Define custom colors
cell_types <- unique(se_obj$all_cells_lvl2)
colors <- rep("grey", length(cell_types))
names(colors) <- cell_types
highlighted <- c("CAF CXCL14+", "Macrophages")
highlighted_colors <- ggsci::pal_igv()(length(highlighted))
colors[highlighted] <- highlighted_colors

# Get the UMAP embeddings
embeddings <- Embeddings(se_obj, "umap")

# Create a data frame with the embeddings and cell type annotations
embeddings_df <- data.frame(embeddings)
embeddings_df$cell_type <- se_obj$all_cells_lvl2

# Calculate the centroid for each cell type to position the labels
centroids <- embeddings_df %>%
  group_by(cell_type) %>%
  summarize(x = mean(UMAP_1), y = mean(UMAP_2))

# Filter to include only the centroids of interest
centroids_to_show <- centroids %>% filter(cell_type %in% highlighted)

# Plot
DimPlot(se_obj, group.by = "all_cells_lvl2", cols = colors, raster = FALSE) + 
  scale_color_manual(values = colors) +
  geom_label(data = centroids_to_show, aes(x = x, y = y, label = cell_type, fill = cell_type), color = "white", size = 5) +
  scale_fill_manual(values = highlighted_colors) +
  theme(legend.text = element_text(size = 25), legend.position = "none") + them_plot
```

# Panel 2

```{r}
data_summary <- se_obj@meta.data %>%
  group_by(Patient_ID, all_cells_lvl2) %>%
  summarise(Count = n(), .groups = 'drop') %>%
  group_by(Patient_ID) %>%
  mutate(Percentage = Count / sum(Count))

pdf(file = "figures/Fig_1/Supp_02_Barplot_Patients_Level2.pdf" %>% here::here() %>% glue::glue(), width = 12, height = 7)
# Create the normalized stacked bar plot
ggplot(data_summary, aes(x = Patient_ID, y = Percentage, fill = all_cells_lvl2)) +
  geom_bar(stat = "identity", position = "fill") +  # Use position "fill" to normalize
  scale_y_continuous(labels = scales::percent_format()) +  # Format y-axis as percent
  labs(title = "Proportional Distribution of Cell Types Per Donor",
       x = "Patient",
       y = "Percentage",
       fill = "Cell Type") +
  theme_minimal(base_size = 14) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) + them_plot +
  scale_fill_manual(values = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50)))
dev.off()

```

Panel 3 - Stromal 

```{r}
Strom = subset(se_obj, subset = annotation_lvl1 %in% "Strom")
Strom
```

```{r}
Strom = Analysis(Strom, res = 0.2, dim = 1:30)
```

```{r}
png(filename = "figures/Fig_1/Supp_02_UMAP_Strom.png" %>% here::here() %>% glue::glue(), width = 500, height = 400)
DimPlot(Strom, group.by = c("all_cells_lvl2"), cols = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50)),raster = F) +
  them_plot +
  theme(legend.text = element_text(size = 15), 
        legend.position = "bottom") + 
  guides(color = guide_legend(override.aes = list(size = 8), nrow = 3)) + ggtitle("Stromal")
dev.off()

```


```{r}
Strom_marker <- wilcoxauc(Strom, 'all_cells_lvl2', seurat_assay = 'SCT')
Strom_marker %>%
    group_by(group) %>%
    dplyr::filter(logFC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10

pdf(file = "figures/Fig_1/Supp_03_Heatmap_Strom.pdf" %>% here::here() %>% glue::glue(), width = 8, height = 12)
DoHeatmap(Strom, features = top10$feature, group.by = "all_cells_lvl2", label = F,group.colors = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50))) +
  scale_color_manual(values = c(ggsci::pal_igv()(50), ggsci::pal_uchicago()(9))) + them_plot
dev.off()

```

# Panel - Myeloid Cells

```{r}
Myeloid = subset(se_obj, subset = annotation_lvl1 %in% "Myeloid")
Myeloid
# Both are express Prolifration genes
Myeloid@meta.data <- Myeloid@meta.data %>%
    dplyr::mutate(
        all_cells_lvl2 = dplyr::case_when(
            all_cells_lvl2 == "Endothelial Proliferation" ~ "mregDC",
            TRUE ~ all_cells_lvl2  # This line ensures that values not matching above conditions are kept as is
            )
        )
```

```{r}
Myeloid = Analysis(Myeloid, res = 0.2, dim = 1:30)
```

```{r}
png(filename = "figures/Fig_1/Supp_02_UMAP_Myeloid.png" %>% here::here() %>% glue::glue(), width = 500, height = 400)
DimPlot(Myeloid, group.by = c("all_cells_lvl2"), cols = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50)),raster = F) +
  theme(legend.text = element_text(size = 15), 
        legend.position = "bottom") + them_plot +
  guides(color = guide_legend(override.aes = list(size = 8), nrow = 3)) + ggtitle("Myeloid")
dev.off()

```


```{r}
Myeloid_marker <- wilcoxauc(Myeloid, 'all_cells_lvl2', seurat_assay = 'SCT')
Myeloid_marker %>%
    group_by(group) %>%
    dplyr::filter(logFC > 1) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10

pdf(file = "figures/Fig_1/Supp_03_Heatmap_Myeloid.pdf" %>% here::here() %>% glue::glue(), width = 8, height = 12)
DoHeatmap(Myeloid, features = top10$feature, group.by = "all_cells_lvl2", label = F,group.colors = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50))) +
  scale_color_manual(values = c(ggsci::pal_igv()(50), ggsci::pal_uchicago()(9))) + them_plot
dev.off()

```


# Panel - CD8

```{r}
T_CD8 = subset(se_obj, subset = annotation_lvl1 %in% "T-CD8")
T_CD8

# Both are express Prolifration genes
T_CD8@meta.data <- T_CD8@meta.data %>%
    dplyr::mutate(
        all_cells_lvl2 = dplyr::case_when(
            all_cells_lvl2 == "CD8 T GZMH+" ~ "CD8 T Proliferation",
            TRUE ~ all_cells_lvl2  # This line ensures that values not matching above conditions are kept as is
            )
        )
```

```{r}
T_CD8 = Analysis(T_CD8, res = 0.2, dim = 1:30)
```

```{r}
png(filename = "figures/Fig_1/Supp_02_UMAP_T_CD8.png" %>% here::here() %>% glue::glue(), width = 500, height = 400)
DimPlot(T_CD8, group.by = c("all_cells_lvl2"), cols = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50)),raster = F) +
  theme(legend.text = element_text(size = 15), 
        legend.position = "bottom") + them_plot +
  guides(color = guide_legend(override.aes = list(size = 8), nrow = 3)) + ggtitle("CD8 T Cells")
dev.off()

```


```{r}
T_CD8_marker <- wilcoxauc(T_CD8, 'all_cells_lvl2', seurat_assay = 'SCT')
T_CD8_marker %>%
    group_by(group) %>%
    dplyr::filter(logFC > 0.5) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10

pdf(file = "figures/Fig_1/Supp_03_Heatmap_T_CD8.pdf" %>% here::here() %>% glue::glue(), width = 8, height = 12)
DoHeatmap(T_CD8, features = top10$feature, group.by = "all_cells_lvl2", label = F,group.colors = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50))) +
  scale_color_manual(values = c(ggsci::pal_igv()(50), ggsci::pal_uchicago()(9))) + them_plot
dev.off()

```

# Panel - CD4

```{r}
T_CD4 = subset(se_obj, subset = annotation_lvl1 %in% "T-CD4")
T_CD4
# Both are express Prolifration genes
T_CD4@meta.data <- T_CD4@meta.data %>%
    dplyr::mutate(
        all_cells_lvl2 = dplyr::case_when(
            all_cells_lvl2 == "CD4 T Proliferation" ~ "CD4 CXCL13",
            all_cells_lvl2 == "CD4 T Activated" ~ "CD4 T Proliferation",
            TRUE ~ all_cells_lvl2  # This line ensures that values not matching above conditions are kept as is
            )
        )

```

```{r}
T_CD4 = Analysis(T_CD4, res = 0.2, dim = 1:30)
```

```{r}
png(filename = "figures/Fig_1/Supp_02_UMAP_T_CD4.png" %>% here::here() %>% glue::glue(), width = 500, height = 400)
DimPlot(T_CD4, group.by = c("all_cells_lvl2"), cols = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50)),raster = F) +
  theme(legend.text = element_text(size = 15), 
        legend.position = "bottom") + them_plot +
  guides(color = guide_legend(override.aes = list(size = 8), nrow = 3)) + ggtitle("CD8 T Cells")
dev.off()

```

```{r}
T_CD4_marker <- wilcoxauc(T_CD4, 'all_cells_lvl2', seurat_assay = 'SCT')
T_CD4_marker %>%
    group_by(group) %>%
    dplyr::filter(logFC > 0.5) %>%
    slice_head(n = 10) %>%
    ungroup() -> top10

pdf(file = "figures/Fig_1/Supp_03_Heatmap_T_CD4.pdf" %>% here::here() %>% glue::glue(),width = 8, height = 12)
DoHeatmap(T_CD4, features = top10$feature, group.by = "all_cells_lvl2", label = F,group.colors = c(ggsci::pal_uchicago()(5),ggsci::pal_igv()(50))) +
  scale_color_manual(values = c(ggsci::pal_igv()(50), ggsci::pal_uchicago()(9))) + them_plot
dev.off()

```

```{r}
"scRNAseq/Final_MSS_Pellka_all_cells.rds" %>%
  here::here() %>%
  glue::glue() %>%
  saveRDS(object = se_obj)
```

```{r}
sessionInfo()
```

