---
author: "Mohamed Abdalfttah"
date: "`r format(Sys.time(), '%d %B, %Y')`"
params:
  Sample: "Default!"
  final_res: "Default!"
title: "Clustering - `r params$Sample` "
output:
  html_document:
    toc: yes
    toc_float: yes
    number_sections: yes
    df_print: paged
editor_options: 
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, out.width = "100%", fig.align='center', 
                      message = FALSE, warning = FALSE)
options(width = 1200)
```

```{r}
library(Seurat)
library(here)
library(glue)
library(tidyverse)
```

```{r}
Analysis_Fun = function(Object, res){
  Object <- SCTransform(Object, assay = "Spatial", verbose = FALSE, return.only.var.genes = F) %>%
  #Object <- Seurat::NormalizeData(Object, verbose = FALSE) %>%
  #Seurat::FindVariableFeatures(selection.method = "vst", nfeatures = 3000) %>%
  #Seurat::ScaleData(verbose = FALSE) %>% 
  Seurat::RunPCA(verbose = FALSE) %>%
  Seurat::FindNeighbors(reduction = "pca", dims = 1:30) %>%
  Seurat::FindClusters(verbose = FALSE, res = res) %>%
  Seurat::RunUMAP(reduction = "pca", dims = 1:30)
  
  
  return(Object)

}

Save_Markers = function(Markers, Path_write){
  mgs_ls = lapply(sort(unique(Markers$cluster)), function(clust) {
  Markers %>%
    dplyr::filter(cluster == clust & pct.1 > 0.3) %>%
    dplyr::arrange(dplyr::desc(avg_log2FC))
    })
  names(mgs_ls) = glue("cluster-{sort(unique(Markers$cluster))}")
  openxlsx::write.xlsx(mgs_ls, file = Path_write)

}

```

```{r}
source(here::here("misc/paths.R"))

#Sample <- "SN124_A938797_Rep2"
#final_res <- 0.3

Sample <- params$Sample
final_res <-  params$res
Path <- "{qc_sp}/{robj_dir}/qc_se_{Sample}.rds" %>%
  glue::glue() %>%
  here::here()
```

```{r, warning=FALSE, message=FALSE}
Data <- readRDS(Path)
```

subset the mitochondrial and ribosomal genes

```{r}
Data <- Data[!grepl("^MT-", rownames(Data)), ]
Data <- Data[ ! grepl('^RP[SL]', rownames(Data)), ]
```


```{r, fig.width=10}
Data <- Analysis_Fun(Object = Data, res = c(0.2, 0.3, 0.4, 0.5))
```

```{r, fig.width=20, fig.width=20}
res <- c("SCT_snn_res.0.2", "SCT_snn_res.0.3", "SCT_snn_res.0.4", "SCT_snn_res.0.5")
sp_dim <- list()
for (i in seq_along(res)) {
  print(SpatialDimPlot(Data, label = FALSE, group.by = res[i]) + 
  guides(fill = guide_legend(override.aes = list(size=10))) + 
  scale_fill_manual(values = ggsci::pal_igv()(50)) +
    DimPlot(Data, group.by = res[i], reduction = "umap",label = TRUE, cols = ggsci::pal_igv()(50),
            pt.size = 2,label.size = 10))
}

```

```{r}
Idents(Data) <- Data@meta.data$SCT_snn_res.0.5
```

```{r, fig.width=10}
SpatialDimPlot(Data, label = FALSE) + 
  guides(fill = guide_legend(override.aes = list(size=10))) + 
  scale_fill_manual(values = ggsci::pal_igv()(50)) +
    DimPlot(Data, reduction = "umap",label = TRUE, cols = ggsci::pal_igv()(50),
            pt.size = 2,label.size = 10)
```

```{r}
markers <- FindAllMarkers(
  object = Data,
  only.pos = TRUE,
  min.pct = 0.25)
```

```{r, fig.width=20, fig.height=20}
markers %>%
    group_by(cluster) %>%
    dplyr::filter(avg_log2FC > 0.5) %>%
    slice_head(n = 20) %>%
    ungroup() -> top10
DoHeatmap(Data, features = top10$gene) + NoLegend()
```

```{r}
"{clust_sp}/{robj_dir}/Markers_{Sample}.xlsx" %>%
    glue::glue() %>%
    here::here() %>%
    Save_Markers(Markers = markers, Path_write = .)

```

```{r}
DefaultAssay(Data) = "Spatial"
"{clust_sp}/{robj_dir}/clust_se_{Sample}.rds" %>%
    glue::glue() %>%
    here::here() %>%
    saveRDS(object = Data, file = .)
```

```{r}
sessionInfo()
```

